EIT-2038 + EIT-2050 | Add proof to Record metadata when retrieved & If record has proof in metadata, don’t retrive it from BLOOCK
bloock/bloock-sdk-js pull request #22
Opened 2022-04-12 12:16 UTC by edutomesco

2022-04-19 10:57 UTC, marcbaque requested changes
You should add unit tests for the proof service.

Can you add a test that checks that, if the setProof functions correctly overrides the record?

2022-04-20 08:31 UTC, alberto-aguado3 commented on src/proof/service/proof.service.test.ts
> +  it('test_retrieve_proof_if_not_document_not_set_proof', async () => {
it could be more clear without the double negative

2022-04-20 08:32 UTC, alberto-aguado3 approved these changes

2022-04-21 09:05 UTC, marcbaque approved these changes

2022-04-21 11:27 UTC, merged